version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: supply_chain
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: